env:
  global:
  - GCP_PROJECT_ID=dbzexampgr301
  - tf_version=0.13.5
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: eU7Tklp4uwQ3To/iWIuH1myrJUeMCePW4KLfu0tdUJNASHYN5NJSN1FIgmT/DhX2Iid29TCdCUCecWzwUtAPnE7Ps9kSxvBHwsodixlOvN/Ud9D3TSRCzsf47oqO+bDRctYUUwKbreAbJqeXoMvyWcItBBCi338+sSzdXo9MJm/iiG6XOifRz9EZ/XxgM1GwHwwpjrxcUnysTD96oKzgVwFvHO9kKwVgYLabDjvKLmZ1zJaeB7NdtMeG/0C4qR1hoOvmvp10o+0DDLEiZ13BI3NZI5TIprbEwF6ZUiRZwo4F5R6wuZRmxI8xkBy/Yk0H0a1IoXzqx353tqdkO0usC+xpppj7dKIGMerZlr2sJuTu/8W1FH11fbxBMgSy3CmPx7aGWzEYgFfvpmKsjiWLJPLGvs/0HInUZTJScqFqQrdB+mqRe/FURkjzO1xfNZYTiOKAK3lbRRc/PyA2rB0tV5cjPuIGOrAyLqj+BP2SVQpu7YOI1a0jUTWVTr4qBc60D+eYAJwSUtrdwK2SIWoDC4xDo7ABYGVAAj+UwKSDcYIhLfgcnV/VDkSGOX4hVjP2u0D+Z2+ozfoGkSeSNfKM0H55Ldz8u2+7Gth3N8wATMdiZ1y3psjGl177HwynmCmIPc8Mme9tQiGiop3ALMOp984BWtYGTAauF8nN8D0cU5Q=
  - secure: svzGBiZbYSI7uJQFHr4bsYHFgCLs+HlJclP2CjMluqZZ/5cn+nIoeemsPH/+9VI5gUnuLydD22IXQfc93/NMOlq9taVRKNRpgq8y/TS8pauMPm/SJRw+T/eoUMKckTqtzdR4iMBwQWh4VIVpzcrX7DXbkwyTTHWR/1S6mLCJu21cirNdeChTbsBRiUTgpfkwx6wgq0//czzUIr9mTkQcC/3VkyHvG3uZw0+7wof62WwU55IcA0FZiA9VxVoO9MUfswE27QzoN//c6DyAAsXsPp3qMfOqs3qiO78VX2HDI31XwavlBPqCUn/f4lCsoLBMMmc7eJYxFuFDcBCQvJGQe/Luhz4kiiIZg6jAHZSj9y5BVph9Q2SDrXpakFaD4k7suQ8KAVMT6vCWMuzlyCwTpUEoppsPe7Zon8FYRb7HFGSTd78QRVaVnXpKcN7IHy2SBuCQdaw5vv8v/5H+cF00gw2XRAG0DyeiIQtI1LOSe+0L1jJAYLi3sRjNmDTcpV+xphOdb5iBjzAZWSKc+U3/cGdeCLGp9y2upfNcH5oXbviIrfZJEH7HMIhxu5enaNfR1yxxzf6fl2gIix6VVVKb9qwKgiKJADq7eKYjiIiFosceZ+4Q131vbWiMnVILHnVuPhvZJePiLy1GFupVPn6vk4mVjjANXfpq7oo7kQmk0mA=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_c63bf1390278_key -iv $encrypted_c63bf1390278_iv
  -in key-file.json.enc -out key-file.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=key-file.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./key-file.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_logz_token=$LOGZ_TOKEN
  export TF_VAR_logz_url=$LOGZ_URL
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
