env:
  global:
  - GCP_PROJECT_ID=dragonballz-296302
  - tf_version=0.13.5
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_61dc43fb09f9_key -iv $encrypted_61dc43fb09f9_iv
  -in terraform_keyfile.json.enc -out terraform_keyfile.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null # Download google cloud sdk and install it
- source "$HOME/google-cloud-sdk/path.bash.inc" #Install google cloud
- gcloud auth activate-service-account --key-file=terraform_keyfile.json #Authenticate in google cloud
- gcloud config set project "${GCP_PROJECT_ID}" #Set active project
- export GOOGLE_APPLICATION_CREDENTIALS=./terraform_keyfile.json #Set google_application_credentials to the decrypted file
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip  #Download terraform
- unzip terraform_"$tf_version"_linux_amd64.zip #Unzip it
- sudo mv terraform /usr/local/bin/ #Move the file
- rm terraform_"$tf_version"_linux_amd64.zip #Remove the zip file for good-practise cleanu
install: true
script:
- |-
  set -ex;
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
