env:
  global:
  - GCP_PROJECT_ID=dbzexampgr301
  - tf_version=0.13.5
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: vvgEJqe1iE5ST8dS8ix39yrrIoXEMME+6F7QPMdEaY7BLrfnzHRpRSSIlciSeu5scYGsUS+17jYl4dZ1BUG+XfxPPx00lA6bnBtVaRbS09PAm5j0ascewlFPXSk/5aHL0NrKLNDSZeoHUJj72XJu4ER92IeQ830mASY63TeHDo/DmujI+sYAA9/HBLk+g3sifLGNQTqzSNpP7kIqcHXdUOyZbhGHICh1orXecnIArbqgkQuKetMcvzdorpCMmSefghboFVNBAriiGsmEDRM72eexRrCmtDpHSB2hNXa+gX8NAOAVDXTtmYEE5AeAvHWcHPIYcBgdU59mKmlG4NiaHqhq70BMeVzalJ7pYD/O0BLeY/ULk0foHx3Qqy2//KdSHpWwwOmD6tvQwfrQtoCgqAh+uvtXitfGkPWcJXnGjM2I283DuGSnxTITL3hRGSm0rrPl1CWDSxWmqdaaxmurt83BAawIWqTm55D8MtRy5n+eLjl9UDa6jLZmMIHhE4vKk384cODPQWjUm9wcEDLn91RzZUmKHJRkc1gzWI4YqQSq69Of3KDkxDODBd5puh0ga8csVqM7PwE1yS1q19pEuKRvdvE9vkYqlpNDChZdkquXP6mPFgDCAk+oB2HMnKQmbzDDfSWtnEb9wXMLJb98Z7soLhCit4CFUEnTcY7UtGw=
  - secure: LOGC4TIfF0Wgffjjq8lhh7TwnFPZyRjMSPkujQyNEskAORow7TRx9zs3qQVfcX8w1qh6Kt6pcqu9whqhJoMCr3mUId1X+irL5L5EA39tW5Xj3Wah5cqpo+bwO+901vkN730aQSCcMWERHxO84MBAR/Yyko3iglIVqtThDWPL+501D9bPqMgvVwFAV1RkoSrBQ0wUCqKBrk0cOhKAYcRicKBAApiRgVxKBVtp0eGILy4z3EAKi+zwaQZ8nillCz3+TIdtjPFH9mkF+BJqZmX4IaNkjXXwd8lkcKtQGQcvqgJOgr5UDmyCPFZHaneN0PYdoXbbji7663Qv/rsrnckRwLuO0NnRcCje4klcREEBcsFVFklz0jYi1AFVnT4cr4cSJpPu0JTkMxOOl+Zlc6L+2tqMwTSQVNNE5LIFpBiNOsu8zyNux9Rj+DIY3eQDXiLHU/xWfsxfAgil1QClgML1f/ZSz6pvA4qgDRWCThJieNDe/8ImFHbCJBS0IMHsrC944fi9NTlrmEa1rYnNn7bhgcpQo8ZMYPqtzpcgLRQm7UBu9/NfBYN+7Nd1wZ5inU0QBYcZbe0Gtf48KZqKkJ3gad3DSIPIpPA8/duMLyd6D7BHdRJoGHO2lRW6rQySHN1+sM+qKsZ8tbcSc42Jm5KzA1/RGGGhsLGhWgx43u1i5Zo=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_c63bf1390278_key -iv $encrypted_c63bf1390278_iv
  -in key-file.json.enc -out key-file.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=key-file.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./key-file.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_logz_token=$LOGZ_TOKEN
  export TF_VAR_logz_url=$LOGZ_URL
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
